=== informalsystems/euc/config.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/informalsystems/euc/main/config.schema.json",
  "title": "Config",
  "description": "Configuration for building binary packages",
  "type": "object",

  "properties": {

    "package": {
      "description": "List of binaries that will be included in the installation package",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "description": "the name of the binary to include",
            "type": "string"
          },
          "build": {
            "description": "the build number defined in GitHub Actions",
            "type": "string"
          },
          "version": {
            "description": "the version number of the binary package on the release file",
            "type": "string"
          },
          "required": ["name", "build", "version"]
        }
      },
      "minItems": 1,
      "uniqueItems": true
    },

    "os": {
      "description": "List of operating systems defined in GitHub Actions that will be built",
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1,
      "uniqueItems": true
    },

    "network": {
      "description": "List of networks that can be built",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "$ref": "https://raw.githubusercontent.com/cosmos/chain-registry/master/chain.schema.json",
          "description": "Partial definitions are accepted, the rest will be filled in from the Cosmos chain registry. Use 'daemon_name' and/or 'chain_name' to define a pointer to the chain registry."
        }
      },
      "minItems": 1,
      "uniqueItems": true
    },

    "tools": {
      "description": "List of tools that can be built",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "description": "name of the tool",
            "type": "string"
          },
          "ref": {
            "description": "the version number defined in Git tag or branches",
            "type": "string"
          },
          "git_url": {
            "description": "the git url of the tool",
            "type": "string"
          },
          "required": ["name", "ref", "git_url"]
        }
      },
      "minItems": 1,
      "uniqueItems": true
    }
  },
    

  "required": ["package", "os", "network"]
}

=== informalsystems/euc/config.json
{
  "package": [
    {
      "name": "regen",
      "build": "v3",
      "version": "v5.0.0"
    },
    {
      "name": "osmosisd",
      "build": "v6",
      "version": "v14.0.0"
    },
    {
      "name": "gaiad",
      "build": "v2",
      "version": "v7.1.0"
    },
    {
      "name": "junod",
      "build": "v4",
      "version": "v11.0.0"
    },
    {
      "name": "akash",
      "build": "v4",
      "version": "v0.20.0"
    },
    {
      "name": "ag0",
      "build": "v3",
      "version": "agoric-upgrade-7-2"
    },
    {
      "name": "cheqd-noded",
      "build": "v3",
      "version": "v0.6.9"
    },
    {
      "name": "ixod",
      "build": "v3",
      "version": "v0.19.1"
    },
    {
      "name": "multisig",
      "build": "v2",
      "version": "v0.4.0"
    },
    {
      "name": "injectived",
      "build": "v2",
      "version": "v1.9.0"
    },
    {
      "name": "strided",
      "build": "v1",
      "version": "v4.0.2"
    },
    {
      "name": "panacead",
      "build": "v1",
      "version": "v2.0.5"
    },
    {
      "name": "quicksilverd",
      "build": "v1",
      "version": "v1.2.0"
    },
    {
      "name": "persistenceCore",
      "build": "v1",
      "version": "v6.1.0"
    },
    {
      "name": "axelar",
      "build": "v1",
      "version": "v0.31.2"
    },
    {
      "name": "okp4d",
      "build": "v1",
      "version": "v6.1.0"
    }
  ],
  "os": [
    "macos-12",
    "ubuntu-20.04"
  ],
  "network": [
    {
      "daemon_name": "gaiad",
      "chain_name": "cosmoshub",
      "codebase": {
        "recommended_version": "v7.1.0"
      }
    },
    {
      "daemon_name": "regen",
      "chain_name": "regen"
    },
    {
      "daemon_name": "osmosisd",
      "chain_name": "osmosis"
    },
    {
      "daemon_name": "junod",
      "chain_name": "juno"
    },
    {
      "daemon_name": "akash",
      "chain_name": "akash"
    },
    {
      "daemon_name": "ag0",
      "chain_name": "agoric",
      "codebase": {
        "recommended_version": "agoric-upgrade-7-2",
        "git_repo": "agoric/ag0"
      }
    },
    {
      "daemon_name": "cheqd-noded",
      "chain_name": "cheqd"
    },
    {
      "daemon_name": "ixod",
      "chain_name": "impacthub",
      "codebase": {
        "recommended_version": "v0.19.1"
      }
    },
    {
      "daemon_name": "nomic"
    },
    {
      "daemon_name": "injectived",
      "chain_name": "injective",
      "codebase": {
        "recommended_version": "v1.9.0",
        "git_repo": "InjectiveLabs/injective-core"
      }
    },
    {
      "daemon_name": "strided",
      "chain_name": "stride",
      "codebase": {
        "recommended_version": "v4.0.2"
        }
    },
    {
      "daemon_name": "panacead",
      "chain_name": "panacea"
    },
    {
      "daemon_name": "quicksilverd",
      "chain_name": "quicksilver"
    },
    {
      "daemon_name": "persistenceCore",
      "chain_name": "persistence"
    },
    {
      "daemon_name": "axelard",
      "chain_name": "axelar",
      "codebase": {
        "recommended_version": "v0.31.2"
      }
    }
  ],
  "tools": [
    {
      "name": "multisig",
      "ref": "v0.4.0",
      "git_url": "informalsystems/multisig"
    },
    {
      "name": "hermes",
      "ref": "v1.2.0",
      "git_url": "informalsystems/hermes"
    }
  ]
}
